# Generated by Django 3.2 on 2021-10-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kings', '0006_auto_20210929_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Till', 'Till')], max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kings.service'),
        ),
    ]
