# Generated by Django 3.2 on 2021-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kings', '0007_auto_20211001_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
