# Generated by Django 3.2 on 2021-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kings', '0009_auto_20211005_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
